### ISSUE TITLE
OWNER 자신의 반려견을 모두 조회하는 기능 구현하기

### ISSUE THREAD

**Issue by cimkoreauniv** [mung-mung/BE#44]
오너의 반려견 정보를 모두 조회할 수 있는 라우트가 필요하다.

반려견 ID만 불러오는 것이 아닌, 반려견 정보 자체를 배열 형태로 전달해주면 될 것 같다.

**Comment by baekgyu-kim** [comment]
"{api 기본 경로}/owner/dogs"로 GET 요청 보내면 현재 로그인 되어있는 owner가 갖고 있는 모든 dogs를 배열 형태로 리턴하도록 구현함
api 명세서에서 "user" 시트아래에 owner 프리픽스 부분 보면 리턴 dto 형식 볼 수 있음
